### ISSUE TITLE
Creating a new quiz through search broken on Android

### ISSUE THREAD

**Issue by quinnajames** [quinnajames/mondain-ionic#1]
The default quiz and custom quizzes work, but search fails to return anything to display on the list, nor does it send the quiz to the server.

**Comment by volucrisscr** [comment]
Should also point out here that some of the quiz input boxes are difficult/impossible to see on Android, and should be made larger.

**Comment by quinnajames** [comment]
Fixed by https://github.com/quinnajames/mondain-ionic/commit/dc7102288c1c95c4e2c6c632f0b6b22a8e5f8dc9
